name: <name>-device-config
version: "0.1"
summary: Ubuntu Device Configuration
description: |
  Device configuration for Ubuntu Core.
confinement: strict
grade: stable
base: core18

plugs:
  web-resources:
    interface: content
    target: $SNAP/static/custom
# this privileged interface for factory reset
#  boot-config:
#    interface: system-files
#    write:
#      - /var/lib/snapd/hostfs/boot/grub/grubenv


apps:
  run:
    command: bin/run
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-setup-control
      - time-control
      - timeserver-control
      - timezone-control
      - system-observe
#      - snapd-control          # this privileged interface for proxy setting
#      - boot-config            # this privileged interface for factory reset
#      - shutdown               # this privileged interface for factory reset

parts:
  application:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc

  static:
    source: static
    plugin: dump
    organize:
      "*": /static/

  bin:
    source: snap/local
    plugin: dump
    organize:
      "*": /bin/

  # this is need for factory reset
#  grub:
#    plugin: nil
#    stage-packages:
#      - to amd64:
#          - grub-common