name: <name>-device-config
version: "0.1"
summary: Ubuntu Device Configuration
description: |
  Device configuration for Ubuntu Core.
#icon: icons/verticals.png
confinement: strict
grade: stable
base: core18

apps:
  run:
    command: bin/run
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  application:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc

  static:
    source: static
    plugin: dump
    organize:
      "*": /static/

  bin:
    source: snap/local
    plugin: dump
    organize:
      "*": /bin/

